### PR TITLE
Generic add/sub

### LINKED ISSUE #88: Add an `integer()` method to `Instant`
Hi, 

I am trying to convert RTIC to use `embedded-time`, however I need access to the underlying ticks of an `Instant` to be able to set the timer's compare register.
Could this be added?

Thanks!

### LINKED ISSUE #89: Duration from `checked_duration_since` cannot be added with `Instant`?
Hi,

I am working on moving RTIC to embedded time, however the following trivial code gives a weird trait bound error that I need help with.
What is causing this as is there a recommended fix?

Code:

```rust
let now = M::now();

match instant.checked_duration_since(&now) {
    None => {
        // ...
    }
    Some(dur) => {
        let new_instant = now + dur; // <-- error

        // ...
    }
}
```

Error:

```
error[E0277]: the trait bound `rtic_core::monotonic::Generic<<M as rtic_core::monotonic::Clock>::T>: FixedPoint` is not satisfied
  --> src/tq.rs:71:47
   |
71 |                         let new_instant = now + dur;
   |                                               ^ the trait `FixedPoint` is not implemented for `rtic_core::monotonic::Generic<<M as rtic_core::monotonic::Clock>::T>`
   |
   = note: required because of the requirements on the impl of `Add<rtic_core::monotonic::Generic<<M as rtic_core::monotonic::Clock>::T>>` for `Instant<M>`
```

### PR DESCRIPTION
**Pull request by korken89**
Hi,

Fixes #89

### CODE REVIEW

**Comment by korken89** [comment]
Ping @PTaylor-us

**Comment by korken89** [comment]
I think this is ready for review @PTaylor-us

**Comment by jhbruhn** [comment]
I am currently in a situation where I need exactly this functionality. How is the state of this being merged? :)

**Comment by jhbruhn** [comment]
Would it make sense to not only add an implementation for Instant - Generic, but also for Generic - Generic?

**Comment by korken89** [comment]
@jhbruhn I have added it.

**Comment by PTaylor-us** [comment]
Does it make sense to add other arithmetic for Generic as well (mult, div)? 

I want to target the next release for this.

**Pull request merged**
