### PR TITLE
Now the extension trait is only implemented for u32

### LINKED ISSUE #95: Proposal: Only implement `Extension` traits for u32 for ergonomy
For the sake of ergonomic use I'd recommend that the `Extension` traits only be implemented for `u32` 
so that the expected operation works. Such as `3.seconds()`, `44.milliseconds()` etc.
Getting rid of the must have `_u32`/`_u64` or similar.

If one wants to be specific type can still use the types directly: `Seconds(1_u64)`.

What are your thoughts on this @PTaylor-us ?

### PR DESCRIPTION
**Pull request by korken89**
Closes #95

### CODE REVIEW

**Comment by PTaylor-us** [comment]
@korken89 I've been thinking a lot about this one. I see pros and cons to it.

Pros
 - more ergonomic creating u32 durations & rates

Cons
 - perhaps not intuitive since a "naked" literal number is usually i32
 - implementation of u32 and u64 (and possibly future additions) are not consistent

Is there any other way we could make these constructors more ergonomic?

**Comment by korken89** [comment]
As I see it, one should make the most common use-case simple (sane defaults).
The shorthand will always be used in simple cases, if a use wants full control they would go with the underlying types.
One thing could be to look into making it so the interface can deduce the correct integer representation from the use.
So one gets a `u64` base type when working with a `u64` based thing, and vice-versa.

**Comment by PTaylor-us** [comment]
Some very good points. I think the u64 can be useful if, say, you need a high precision "infinite" clock source (maybe for a system clock for log timestamps), but I agree that those could be considered a special case. Ok, I think you've sold me on it. I'll take another quick look again this evening and merge it. Thanks!

**Comment by korken89** [comment]
Hi, @PTaylor-us this seems to not have been merged to `master`

**Pull request merged**
