### PR TITLE
Add serde support to concrete units

### LINKED ISSUE #55: Add serde Serialize/Deserialize impls to types?
Per the [API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-serde)

### PR DESCRIPTION
**Pull request by mattico**
Fixes #55

### CODE REVIEW

**Comment by mattico** [comment]
The CI failure is unrelated: https://github.com/rust-lang/rust/issues/77638

**Comment by mattico** [comment]
Includes https://github.com/FluenTech/embedded-time/pull/78 to get CI working on nightly.

**Comment by PTaylor-us** [comment]
Thanks for this! I'll get this reviewed and pulled.

**Review by korken89 — APPROVED** [review]
This looks good to me. Thanks for the effort!

**Comment by korken89** [comment]
Ping @PTaylor-us

**Comment by PTaylor-us** [comment]
Is there a downside to putting it behind a feature flag?

**Comment by mattico** [comment]
Enabling the serde support increases the number of built crates from 16 to 30 and doubles the clean build time on my 16-thread machine from 9s to 18s.

We could enable the feature by default but it is nice to provide the option to disable it for people who care about such things.

**Comment by korken89** [comment]
It's common practice to have `serde` support behind a flag, as it is not the main aim of the library. Plus compile time bloat as `serde` is a beast :)

**Comment by PTaylor-us** [comment]
Thank you for this!

**Pull request merged**
